Insert into staff values(1,'Mihalis Yannakakis','Mon 4-6pm','455 Computer Science Building');
Insert into staff values(2,'Kenneth A. Ross','Mon 2:30-3:30pm, Thu 2:30-3:30pm','510 Computer Science Building');
Insert into staff values(3,'Steven K. Feiner','Mon 1-2pm, Wed 1-2pm','609 Schapiro CEPSR');
Insert into staff values(4,'Shree K. Nayar','Wed 2-3pm','621 Schapiro CEPSR');
Insert into staff values(5,'Jason Nieh','Thu 9-10am','518 Computer Science Building');
Insert into staff values(6,'Eitan Grinspun','Tue 2-3pm','330 Computer Science Building');
Insert into staff values(7,'Daniel Hsu','Mon 1-3pm','702 CEPSR');
Insert into staff values(8,'Vishal Misra','Tue 3-4pm','512 Computer Science Building');
Insert into staff values(9,'Rocco Servedio','Fri 10-12am','517 Computer Science Building');
Insert into staff values(10,'Dragomir Radev','Tues 6-7pm, Thurs 6-7pm','722 CEPSR');
Insert into staff values(11,'Junde Huang','Wed 2-4pm, Fri 2-4pm','TA Room');
Insert into staff values(12,'Marshall Ball','Mon 6-8pm','TA Room');
Insert into staff values(13,'Rahul Tewari','Wed 4-6pm','TA Room');
Insert into staff values(14,'Wenting Yin','Tue 3-5pm','TA Room');
Insert into staff values(15,'Yash Parikh','Tue, 3-4pm, Thu, 12-1pm','TA room');
Insert into staff values(16,'Pranita Dewan','Tue 12-1pm, Wed 1-2pm','TA room');
Insert into staff values(17,'Muyuan Liu','Mon 10-11am, Fri 1-2pm','TA room');
Insert into staff values(18,'Nimai Buch','Tue 2-3pm, Fri 3-4pm','TA room');
Insert into staff values(19,'Ajoy Savio Fernandes','Wed 2:30–4:30pm','TA room');
Insert into staff values(20,'Shloka Kini','Mon 6-8pm','TA room');
Insert into staff values(21,'Rahul Tewari','Tue 4-6pm','TA room');
Insert into staff values(22,'Manasvi Vohra','Thu 3-5pm','TA room');
Insert into staff values(23,'Olivia Winn','Mon 2-4pm','6LW4 Schapiro CEPSR');
Insert into staff values(24,'Robert Colgan','Tue 2-4pm','6LW4 Schapiro CEPSR');
Insert into staff values(25,'Xiaotang Wang','Thu 2-4pm','TA Room');
Insert into staff values(26,'Shih-Wei Li','Mon 10-12am, Wed 10-12','TA Room');
Insert into staff values(27,'Jintack Lim','Wed 4-6pm,Thu 2-4pm','TA Room');
Insert into staff values(28,'David Tagatac','Fri 2-4pm','TA Room');
Insert into staff values(29,'Lingmei Weng','Mon 12-2pm','TA Room');
Insert into staff values(30,'Liyuan Zheng','Tue 2-4pm','TA Room');