Insert into student(student_id,name,enroll_interval,student_type) values('yf2338','Yuan Feng',6,1);
Insert into student(student_id,name,enroll_interval,student_type) values('mg3534','Mingfei Ge',6,1);
Insert into student(student_id,name,enroll_interval,student_type) values('cd2789','Chengcheng Du',6,1);
Insert into student(student_id,name,enroll_interval,student_type) values('ps2839','Peng Song',6,1);
Insert into student(student_id,name,enroll_interval,student_type) values('ys2318','Yun Sun',6,1);
Insert into student(student_id,name,enroll_interval,student_type) values('lj2351','Lina Jin',6,1);
Insert into student(student_id,name,enroll_interval,student_type) values('cc3736','Chao Chen',6,1);
Insert into student(student_id,name,enroll_interval,student_type) values('jl4368','Jianqiao Li',6,1);
Insert into student(student_id,name,enroll_interval,student_type) values('gbp2105','Gwendolyn B Pfetsch',3,1);
Insert into student(student_id,name,enroll_interval,student_type) values('mnv2107','Manasvi N Vohra',3,0);
